framework:
    notifier:
        chatter_transports:
            slack: '%env(SLACK_DSN)%'
        #    telegram: '%env(TELEGRAM_DSN)%'
        texter_transports:
            ovhcloud: '%env(OVHCLOUD_DSN)%'
        #    nexmo: '%env(NEXMO_DSN)%'
        channel_policy:
            # use chat/slack, chat/telegram, sms/twilio or sms/nexmo
            urgent: ['sms/ovhcloud']
            high: ['email']
            medium: ['chat/slack']
            low: ['browser']
        admin_recipients:
            - { email: noble.jka@protonmail.com }